---
apiVersion: traefik.containo.us/v1alpha1
kind: Middleware
metadata:
  name: stripprefixes-kibana
  namespace: kommander
spec:
  stripPrefix:
    prefixes:
    - /kibana
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  annotations:
    kubernetes.io/ingress.class: kommander-traefik
    traefik.ingress.kubernetes.io/router.tls: "true"
    traefik.ingress.kubernetes.io/router.middlewares: kommander-stripprefixes-kibana@kubernetescrd,kommander-forwardauth@kubernetescrd
    #   
  labels:
    app: kibana
  name: kibana-ingress
spec:
  rules:
  - http:
      paths:
      - backend:
          service:
            name: kibana-kb-http
            port:
              number: 5601
        path: /kibana
        pathType: Prefix